# NumPy

NumPy is a Python Library

It is used for working with arrays

It is short for "Numerical Python"

It is used for computation and processing of single and multi dimensional array of elements

Smaller memory consumption and better runtime behavior

In [80]:
# To install the library
# pip install numpy

import numpy

In [81]:
import numpy as np

In [82]:
a = np.array([1,4,5])
print(a)

[1 4 5]


In [83]:
a = np.array([1,2,4], dtype = float)
print(a)

[1. 2. 4.]


In [84]:
a = np.array([1,2,4], dtype = int)
print(a)

[1 2 4]


In [85]:
b = np.array([[1,2,3], [4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [86]:
type(b)

numpy.ndarray

In [87]:
c = np.array([[3,4,6],[2,4,5],[9,8,7]])
print(c)

[[3 4 6]
 [2 4 5]
 [9 8 7]]


In [88]:
#Get Dimensions of a numpy array
a.ndim

1

In [89]:
b.ndim

2

In [90]:
c.ndim

2

In [91]:
d = np.array([[[[3,4,5],[6,7,7],[3,2,3]]]])
print(d)

[[[[3 4 5]
   [6 7 7]
   [3 2 3]]]]


In [92]:
d.ndim

4

# Why Use NumPy?

In Traditional Python Programming, we have lists that serve the purpose of arrays, but they are slow to process

NumPy aims to provide an array object that is up to 50x faster than traditional Python lists

The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy

Arrays are very frequently used in data science, where speed and resources are very important


In [93]:
a

array([1, 2, 4])

In [94]:
# Get a shap of a numpy array
a.shape

(3,)

In [95]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
b.shape

(2, 3)

In [97]:
c

array([[3, 4, 6],
       [2, 4, 5],
       [9, 8, 7]])

In [98]:
c.shape

(3, 3)

In [99]:
a

array([1, 2, 4])

In [100]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [101]:
b.dtype

dtype('int64')

In [102]:
a_int = np.array([1.1,2.1,3.4])
print(a_int)

[1.1 2.1 3.4]


In [103]:
a_int.dtype

dtype('float64')

In [104]:
# Accessing/Changing specific elements, rows and columns etc

a = np.array([[1,2,3,4,5,6,7],[7,5,4,3,2,2,1]])
print(a)

[[1 2 3 4 5 6 7]
 [7 5 4 3 2 2 1]]


In [105]:
a.ndim

2

In [106]:
#Get a specific element [r,c]
a[0,3]

np.int64(4)

In [107]:
a[1, 5]

np.int64(2)

In [108]:
#Get a specific row from a numpy array
a[0:]

array([[1, 2, 3, 4, 5, 6, 7],
       [7, 5, 4, 3, 2, 2, 1]])

In [109]:

a[0, : ]

array([1, 2, 3, 4, 5, 6, 7])

In [110]:
a[1, : ]

array([7, 5, 4, 3, 2, 2, 1])

In [111]:
#Get a specific column from a numpy array
a[ : , 0]

array([1, 7])

In [112]:
a

array([[1, 2, 3, 4, 5, 6, 7],
       [7, 5, 4, 3, 2, 2, 1]])

In [113]:
a[0,4] = 50
print(a)

[[ 1  2  3  4 50  6  7]
 [ 7  5  4  3  2  2  1]]


In [114]:
a

array([[ 1,  2,  3,  4, 50,  6,  7],
       [ 7,  5,  4,  3,  2,  2,  1]])

# Zeros/Ones method in NumPy

In [115]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [116]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [117]:
np.ones((4,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [118]:
np.ones((4,4), dtype = 'int')

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [119]:
np.full((3,3), 40, dtype = 'float')

array([[40., 40., 40.],
       [40., 40., 40.],
       [40., 40., 40.]])

In [120]:
np.full((3,3), 50, dtype = 'int')

array([[50, 50, 50],
       [50, 50, 50],
       [50, 50, 50]])

In [121]:
np.random.rand(4,4)

array([[0.20891559, 0.84933737, 0.502686  , 0.1539579 ],
       [0.40157649, 0.69558669, 0.17256905, 0.2285879 ],
       [0.61495609, 0.38178567, 0.68143169, 0.15642095],
       [0.21080196, 0.66292901, 0.28201697, 0.71415582]])

In [122]:
np.random.randint(-3,1, size = (3,3))

array([[ 0, -2, -3],
       [-3, -1, -1],
       [ 0, -3,  0]], dtype=int32)

In [123]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [124]:
np.identity(3)


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Extract all the first 3 rows of the last 5 columns in a given numpy 2D array's

In [125]:
a = np.array([[1,2,3,4,5,6],
              [10,20,30,40,50,60],
              [8,7,3,4,6,4],
              [11,22,33,44,5,55],
              [88,3,1,5,6,7]])

In [126]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [ 8,  7,  3,  4,  6,  4],
       [11, 22, 33, 44,  5, 55],
       [88,  3,  1,  5,  6,  7]])

In [127]:
a.ndim

2

In [128]:
a[ : 3, -5: ]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [ 7,  3,  4,  6,  4]])

Give a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

In [129]:
n=5

In [130]:
import numpy as np 

# create an (nxn) array array with all zeros 
z = np.zeros((n,n), dtype='int')
print(z)

[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]


In [131]:
# Make the middle row and column all 1s 

z[n//2, : ] =1
z[ : , n//2] = 1

#Print the final value of z
print(z)

[[0 0 1 0 0]
 [0 0 1 0 0]
 [1 1 1 1 1]
 [0 0 1 0 0]
 [0 0 1 0 0]]


Just to help you understand about n//2

In [132]:
a = np.array([[2,5,7,9,8,1,2],
              [10,20,30,40,50,60,70],
              [12,9,0,6,3,2,3],
              [13,9,0,2,3,4,5],
              [4,6,7,8,9,1,6]])

In [133]:
a

array([[ 2,  5,  7,  9,  8,  1,  2],
       [10, 20, 30, 40, 50, 60, 70],
       [12,  9,  0,  6,  3,  2,  3],
       [13,  9,  0,  2,  3,  4,  5],
       [ 4,  6,  7,  8,  9,  1,  6]])

In [134]:
a[5//2, : ] =1

In [135]:
a[ : ,5//2] =1

In [136]:
a

array([[ 2,  5,  1,  9,  8,  1,  2],
       [10, 20,  1, 40, 50, 60, 70],
       [ 1,  1,  1,  1,  1,  1,  1],
       [13,  9,  1,  2,  3,  4,  5],
       [ 4,  6,  1,  8,  9,  1,  6]])

In [137]:
a[ : ,n//2] =1
print(a)

[[ 2  5  1  9  8  1  2]
 [10 20  1 40 50 60 70]
 [ 1  1  1  1  1  1  1]
 [13  9  1  2  3  4  5]
 [ 4  6  1  8  9  1  6]]


Arithmetic Operations with NumPy - Maths + Stats

In [138]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [139]:
a+2

array([3, 4, 5, 6])

In [140]:
#Do it for -,/,*,//,** - Almost all the operations are satisfied

a**3

array([ 1,  8, 27, 64])

In [141]:
a

array([1, 2, 3, 4])

In [142]:
a.min()

np.int64(1)

In [143]:
a.max()

np.int64(4)

In [144]:
np.max(a)

np.int64(4)

In [145]:
a.mean()

np.float64(2.5)

In [146]:
a= np.array([[1,2,3,4],[5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [147]:
np.max(a)

np.int64(8)

In [148]:
a.max()

np.int64(8)

In [149]:
np.max(a, axis=1)

array([4, 8])

In [150]:
np.max(a, axis=0)

array([5, 6, 7, 8])

In [151]:
np.min(a, axis=0)

array([1, 2, 3, 4])

In [152]:
np.sum(a, axis=1)

array([10, 26])

Array from 1 to 10

In [153]:
num = np.arange(1, 11)
print(num)

[ 1  2  3  4  5  6  7  8  9 10]


Zeros array(3x3)

In [154]:
x = np.zeros((3,3))

In [155]:
print(x)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


Ones array (2x4)

In [157]:
arr = np.ones((2, 4))

print(arr)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]


Numbers from 10 to 50

In [158]:
num = np.arange(10, 51)
print(num)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50]


Even number between 2 to 20

In [159]:
arr = np.arange(2,21,2)
print(arr)

[ 2  4  6  8 10 12 14 16 18 20]


Addition, subtration, multiplication, division

In [160]:
a = np.array([3,2,1])
b = np.array([6,7,8])

print(a+b)
print(a-b)
print(a*b)
print(a/b)

[9 9 9]
[-3 -5 -7]
[18 14  8]
[0.5        0.28571429 0.125     ]


Multiply array by 5

In [162]:
arr = np.array([4,5,6])
mul = arr*5
print(mul)

[20 25 30]


Sum and mean

In [163]:
arr = np.array([3,4,5])
print(np.sum(arr))
print(np.mean(arr))

12
4.0


Max and min

In [164]:
arr = np.array([5,6,7,3,4,7,8,9,1,55,62,45,66,76])
print(np.max(arr))
print(np.min(arr))

76
1


Reshape into (3,4)

In [166]:
arr = np.arange(1,13)
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [169]:
arr = np.arange(3, 28)
print(arr.reshape(5,5))

[[ 3  4  5  6  7]
 [ 8  9 10 11 12]
 [13 14 15 16 17]
 [18 19 20 21 22]
 [23 24 25 26 27]]


Elements index 1 to 3

In [170]:
arr = np.array([10,20,33,4,45,334,552,343])
arr[1:4]

array([20, 33,  4])

Second row

In [171]:
mat = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])
print(mat[1])

[4 5 6]


Third column

In [172]:
print(mat[ : ,2])

[3 6 9]


In [173]:
print(mat[ : ,1])

[2 5 8]


Elements greater than 25

In [174]:
arr = np.array([10,20,30,40,50,60])

print(arr[arr>25])

[30 40 50 60]


Add 10 to each element

In [175]:
arr = np.array([3,4,5])
print(arr+10)

[13 14 15]


Add [1,2,3] to each row

In [176]:
A = np.array([[2,2,2],
              [1,2,2]])
B = np.array([1,2,3])

print(A+B)

[[3 4 5]
 [2 4 5]]


Five random numbers

In [181]:
print(np.random.rand(5))

[0.53989282 0.89285655 0.24461704 0.9480081  0.72799564]


Ten random integers (1-100)

In [183]:
print(np.random.randint(1,101,10))

[39 77 81 48 36 97 73 76 45 66]


Matrix transpose

In [184]:
A = np.array([[1,2],
              [3,4]])
print(A.T)

[[1 3]
 [2 4]]


Matrix multiplication

In [186]:
A = np.array([[1,3],
              [3,4]])
B = np.array([[5,6],
              [2,3]])

print(np.dot(A,B))  # or print(A @ B)

[[11 15]
 [23 30]]
